### ISSUE TITLE
Whitespace is removed from CSS in <style> elements

### ISSUE THREAD

**Issue by RohanTalip** [svg/svgo#1067]
Using this config for svgo 1.1.1:
```
plugins:
- convertStyleToAttrs: false
- inlineStyles: false
- minifyStyles: false

js2svg:
  pretty: true
  indent: 2
```

... this file:
```
svg viewBox="0 0 2 2">
  <style>
    .a {
      stroke: red;
    }
    .b {
      stroke: black;
    }
  </style>
  <path class="a" d="M0 0h1"/>
  <path class="b" d="M0 0v1"/>
</svg>
```

... gets converted into:
```
<svg viewBox="0 0 2 2">
  <style>
    .a { stroke: red; } .b { stroke: black; }
  </style>
  <path class="a" d="M0 0h1"/>
  <path class="b" d="M0 0v1"/>
</svg>
```

i.e. The CSS styles lose the previous whitespace.

(Ignore that this is pretty much a useless SVG file; it's only for demonstrating this issue.)

I couldn't tell at a glance if there was any configuration which disabled this behaviour (i.e. left the whitespace in the style element untouched).  Is there a plugin that could be disabled that would prevent this behaviour?

Where in the svgo code is this change being done?
