### ISSUE TITLE
TypeError on some plugins (addAttributesToSVGElement and removeAttrs)

### ISSUE THREAD

**Issue by snirp** [svg/svgo#1115]
This is the same config I used a while back, but now it returns an error on `addAttributesToSVGElement` and `removeAttrs` plugins. I tried reverting to older versions of svgo (1.1.0  and 1.0.2), but to no avail.

Here is the config: 

```yaml
plugins:
  - removeViewBox: false
  - removeDimensions: true
  - addAttributesToSVGElement:
    attributes:
      - fill: currentColor
  - removeAttrs:
    attrs:
      - fill
      - fill-rule
      - stroke
      - stroke-width
```

And the error:

```bash
TypeError: Cannot read property 'fn' of null
    at /usr/local/lib/node_modules/svgo/lib/svgo/config.js:134:64
    at Array.forEach (<anonymous>)
    at extendConfig (/usr/local/lib/node_modules/svgo/lib/svgo/config.js:126:24)
    at module.exports (/usr/local/lib/node_modules/svgo/lib/svgo/config.js:31:20)
    at new SVGO (/usr/local/lib/node_modules/svgo/lib/svgo.js:21:19)
    at Cmd.<anonymous> (/usr/local/lib/node_modules/svgo/lib/svgo/coa.js:245:16)
    at /usr/local/lib/node_modules/svgo/node_modules/coa/lib/cmd.js:417:45
    at _fulfilled (/usr/local/lib/node_modules/svgo/node_modules/q/q.js:854:54)
    at /usr/local/lib/node_modules/svgo/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/svgo/node_modules/q/q.js:816:13)
```

Commenting out both plugins stops the error from occurring.

**Comment by cadejscroggins** [comment]
@snirp I was having this issue with `removeAttrs` and fixed it like this:
```yml
plugins:
  - removeAttrs: { attrs: (fill|fill-rule|stroke|stroke-width) }
```

**Comment by GreLI** [comment]
YML requires extra padding for collection items properties like this:
```yml
plugins:
  - removeViewBox: false
  - removeDimensions: true
  - addAttributesToSVGElement:
      attributes:
        - fill: currentColor
  - removeAttrs:
      attrs:
        - fill
        - fill-rule
        - stroke
        - stroke-width
```
JSON can be used for config as well.
