### ISSUE TITLE
remove quotes from CSS URL functions

### ISSUE THREAD

**Issue by zamfofex** [svg/svgo#1142]
Hello! Personally, I prefer to write CSS `url` functions as `url('#xxx')` as opposed to `url(#xxx)` in my SVG source. It would be cool if SVGO could be able to identify these and convert them to the shorter (latter) form.

I was able to write a custom plugin that did the trick for me, but I feel like some modifications would be appropriate to make it accept double quotes, as well as URL functions that do not take up the full attribute value.

```JavaScript
{
	type: "perItem",
	fn: item =>
	{
		if(!item.isElem()) return
		
		for(let name in item.attrs)
		{
			let attr = item.attrs[name]
			let value = attr.value
			if(value.startsWith("url('") && value.endsWith("')"))
				attr.value = `url(${value.slice(5, -2)})`
		}
	},
}
```

**Comment by XhmikosR** [comment]
@TrySound this doesn't happen in the latest csso:

```css
.foo { background: url("#xxx") }
.bar { background: url('#xxx') }
```

```css
.foo{background:url(#xxx)}.bar{background:url(#xxx)}
```

Is there any other place that this could be missed?
