### ISSUE TITLE
SVGO CLI doesn't apply config for icons

### ISSUE THREAD

**Issue by frontenddeveloping** [svg/svgo#1241]
Node 10.19.0
I installed svgo as `npm i -g svgo`
I use command `svgo src/path-to-cons/*.svg --config=.svgo.yml`, but config doesn't apply
Config:
```
multipass: true

plugins:
    - removeViewBox: true
    - removeAttr:
        attrs: '(fill|stroke)'
    - sortAttrs: true
    - sortDefsChildren: true
    - removeStyleElement: true
    - removeScriptElement: true
```

I still have viewBox, fill and strok attrs
