### ISSUE TITLE
Make svgo a pre-commit hook

### ISSUE THREAD

**Issue by lcnittl** [svg/svgo#1287]
Would you consider making svgo a [pre-commit](https://pre-commit.com) hook, by adding a [`.pre-commit-hooks.yaml`](https://pre-commit.com/#creating-new-hooks) file to your repository? This would allow people to have svg files in their repositories to automatically check them whenever they want to commit them.

I can file a PR for the `.pre-commit-hooks.yaml`, if you agree.

Thanks for your consideration!

**Comment by TrySound** [comment]
This is out of this project scope. Feel free to create new package wrapper around svgo.

**Comment by codingjoe** [comment]
In case someone is still looking in 2026. Just add this to your config:

```yaml
repos:
  - repo: local
    hooks:
      - id: svgo
        name: svgo
        language: node
        additional_dependencies: [svgo]
        entry: svgo
        args: [--pretty, --multipass, --indent, "2"]
        require_serial: true
        pass_filenames: true
        types: [svg]
```
