### ISSUE TITLE
Specify yaml config file failed  "Invalid or unexpected token"

### ISSUE THREAD

**Issue by Jancat** [svg/svgo#1343]
This works without config file:
```
svgo -r -f ./assets
```

Specify yaml config file failed:
```
$ svgo -r -f ./assets --config ./config/.svgo.yml
Invalid or unexpected token
```

**./config/.svog.yml**:
```yml
plugins:
  - removeXMLNS: true
  - removeViewBox: false
  - removeDimensions: true
  - sortAttrs: true

js2svg:
  pretty: true
  indent: ' '
```

**svgo 2.0.1**
