### ISSUE TITLE
moveElemsAttrsToGroup loses color 

### ISSUE THREAD

**Issue by kasbah** [svg/svgo#478]
- [original](http://kaspar.h1x.com/arduino-original.svg)
- [without moveElemsAttrsToGroup](http://kaspar.h1x.com/arduino-noElemAttrToGroups.svg)
- [with moveElemsAttrsToGroup](http://kaspar.h1x.com/arduino-ElemAttrToGroups.svg)

Config used: 

``` yaml
plugins:
  - removeDoctype                  : true
  - removeXMLProcInst              : true
  - removeComments                 : true
  - removeMetadata                 : true
  - removeEditorsNSData            : true
  - cleanupAttrs                   : true
  - minifyStyles                   : true
  - convertStyleToAttrs            : true
  - cleanupIDs                     : true
  - removeRasterImages             : true
  - removeUselessDefs              : true
  - cleanupNumericValues           : true
  - cleanupListOfValues            : true
  - convertColors                  : true
  - removeUnknownsAndDefaults      : true
  - removeNonInheritableGroupAttrs : true
  - removeUselessStrokeAndFill     : true
  - removeViewBox                  : true
  - cleanupEnableBackground        : true
  - removeHiddenElems              : true
  - removeEmptyText                : true
  - convertShapeToPath             : true
  - moveElemsAttrsToGroup          : false
  - moveGroupAttrsToElems          : true
  - collapseGroups                 : true
  - convertPathData                : true
  - convertTransform               : true
  - removeEmptyAttrs               : true
  - removeEmptyContainers          : true
  - mergePaths                     : true
  - removeUnusedNS                 : true
  - transformsWithOnePath          : true
  - sortAttrs                      : true
  - removeTitle                    : true
  - removeDesc                     : true
  - removeDimensions               : true
  - removeAttrs                    : true
  - addClassesToSVGElement         : false
  - removeStyleElement             : false

```
