### ISSUE TITLE
removeAttrs not working at all

### ISSUE THREAD

**Issue by pixelass** [svg/svgo#558]
```yml
plugins:  
  - removeAttrs: 
    - attrs: 'fill'
```

input 

```html
<svg>
  <path fill="#f00" d="M4 4h24v24h-24z"></path>
</svg>
```

output 

```html
<svg>
  <path fill="#f00" d="M4 4h24v24h-24z"></path>
</svg>
```

expected output 

```html
<svg>
  <path d="M4 4h24v24h-24z"></path>
</svg>
```

I tested the config file with other plugins and they work separately and in combiation with this one, though `removeAttrs` does no change the code in any way

**Comment by jonrimmer** [comment]
I ran into the same problem. The example in the removeAttrs source is wrong.

You need to set removeAttrs to true, as well as include its params:

```yml
plugins:
  - removeAttrs: true
    - attrs: 'fill'

**Comment by jonrimmer** [comment]
I had the same problem.

The yml should be:

```yml
plugins:  
  - removeAttrs: 
      attrs: 'fill'
```
