### ISSUE TITLE
Enable plugin via CLI

### ISSUE THREAD

**Issue by jesseflorig** [svg/svgo#707]
How do you use the `enable` plugin flag via the CLI? I tried the following:
```
svgo --enable=removeViewBox
svgo --enable='removeViewBox'
svgo --enable=[removeViewBox]
```
The options documentation seems to be somewhat misleading.

**Comment by GreLI** [comment]
```
svgo --enable=<plugin-name>
```
The first one should work. Plugins have their own conditions though (e.g. `removeViewBox` removes only attributes like `viewBox="0 0 <width> <height>"`).

**Comment by chenxiaochun** [comment]
exec the `svgo --enable=removeViewBox`, show all help information?
My version is `svgo@1.0.3`
```
Usage:
  svgo [OPTIONS] [ARGS]


Options:
  -h, --help : Help
  -v, --version : Version
  -i INPUT, --input=INPUT : Input file, "-" for STDIN
  -s STRING, --string=STRING : Input SVG data string
  -f FOLDER, --folder=FOLDER : Input folder, optimize and rewrite all *.svg files
  -o OUTPUT, --output=OUTPUT : Output file or folder (by default the same as the input), "-" for STDOUT
  -p PRECISION, --precision=PRECISION : Set number of digits in the fractional part, overrides plugins params
  --config=CONFIG : Config file or JSON string to extend or replace default
  --disable=DISABLE : Disable plugin by name
  --enable=ENABLE : Enable plugin by name
  --datauri=DATAURI : Output as Data URI string (base64, URI encoded or unencoded)
  --multipass : Enable multipass
  --pretty : Make SVG pretty printed
  --indent=INDENT : Indent number when pretty printing SVGs
  -q, --quiet : Only output error messages, not regular status messages
  --show-plugins : Show available plugins and exit
```

**Comment by iology** [comment]
How to enable multiple plugins?

**Comment by chenxiaochun** [comment]
@iology, I also don't know in the command line. But you can place a `.svgo.yml` in your project. For example, i use it like this:

```
# replace default config

# multipass: true
# full: true

plugins:

  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2
  - removeViewBox: false
  - removeDimensions: true
  - removeStyleElement: true
  - mergePaths: true
  - removeUselessDefs: true
  - collapseGroups: true
  - prefixIds: true
    

# configure the indent (default 4 spaces) used by `--pretty` here:
#
# @see https://github.com/svg/svgo/blob/master/lib/svgo/js2svg.js#L6 for more config options
#
# js2svg:
#  pretty: true
#  indent: '  '

```
