### ISSUE TITLE
[REQUEST] Remove data-name="Layer 1" from SVGs

### ISSUE THREAD

**Issue by SebKay** [svg/svgo#799]
Is there any way that when optimising SVGs, SVGO would be able to remove the data-name="Layer 1" added to certain elements by Adobe Illustrator?

Thanks!

**Comment by GreLI** [comment]
`data-*` attrs are being preserved by `removeUnknownsAndDefaults` plugin by default since it may have some useful data for scripts. But you can turn off `keepDataAttrs` option in [your config](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md#1-config). Like this:
```yml
plugins:
  - removeUnknownsAndDefaults:
      keepDataAttrs: false
```
