### ISSUE TITLE
Setting convertColors.currentColor does not work from the .svgo.yml

### ISSUE THREAD

**Issue by marcofugaro** [svg/svgo#967]
This is my .svgo.yml
```yml
multipass: true
js2svg:
  pretty: true
  indent: '  '
plugins:
  - sortAttrs
  - removeDimensions
  - convertColors:
    - currentColor: true
```

Basically it's ignoring the `currentColor: true`. Otherwise all the other plugins are respected.

**Comment by GreLI** [comment]
Why you making it a list? (Dash before `currentColor`.)

**Comment by GreLI** [comment]
```yml
plugins:
  - convertColors:
      currentColor: true
```
should work.
